definitions:
  apiserver.depositRequest:
    properties:
      amount:
        example: 99.9
        type: number
      user_id:
        example: 1
        type: integer
    type: object
  apiserver.transferRequest:
    properties:
      amount:
        example: 99.9
        type: number
      from:
        example: 1
        type: integer
      to:
        example: 2
        type: integer
    type: object
  apiserver.withdrawRequest:
    properties:
      amount:
        example: 99.9
        type: number
      user_id:
        example: 1
        type: integer
    type: object
  model.Transaction:
    properties:
      amount:
        example: 12.34
        type: number
      details:
        example: some details
        type: string
      timestamp:
        example: 1643756522
        type: integer
      tx_id:
        example: 123
        type: integer
      type:
        example: deposit/withdraw
        type: string
      user_id:
        example: 1
        type: integer
    type: object
  model.User:
    properties:
      balance:
        example: 100.51
        type: number
      user_id:
        example: 1
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  title: User's Balance Service
  version: "1.0"
paths:
  /balance:
    get:
      consumes:
      - application/json
      description: Returns the account balance by user id
      operationId: balance
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      tags:
      - User data
  /deposit:
    post:
      consumes:
      - application/json
      description: Adding funds to the user's balance
      operationId: deposit
      parameters:
      - description: Deposit info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/apiserver.depositRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Transaction'
      tags:
      - Funds
  /transactions:
    get:
      consumes:
      - application/json
      description: Provides paginated list of user transactions
      operationId: transactions
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      - default: 1
        description: Page
        in: query
        name: page
        type: integer
      - default: 10
        description: Limit
        in: query
        name: limit
        type: integer
      - description: Order
        enum:
        - desc
        - asc
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Transaction'
            type: array
      tags:
      - User data
  /transfer:
    post:
      consumes:
      - application/json
      description: Transfers funds from one user to another
      operationId: transfer
      parameters:
      - description: Transfer info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/apiserver.transferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Transaction'
            type: array
      tags:
      - Funds
  /withdraw:
    post:
      consumes:
      - application/json
      description: Withdrawal of funds from the user's balance
      operationId: withdraw
      parameters:
      - description: Withdrawal info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/apiserver.withdrawRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Transaction'
      tags:
      - Funds
swagger: "2.0"
